export { default as Home } from './Home';
export { default as CVBuilder } from './CVBuilder';
export { default as AboutUs } from './AboutUs';
export { default as FlagshipEvents } from './FlagshipEvents';
export { default as Recruiters } from './Recruiters';
export { default as SinglePost } from './SinglePost';
export { default as StudentsCorner } from './StudentsCorner';
export { default as AllPosts } from './AllPosts';
export { default as ContactUs } from './ContactUs';
